### ISSUE TITLE
Please show a demo ^_^

### ISSUE THREAD

**Issue by roadahead** [crodas/TextRank#1]

**Comment by crodas** [comment]
What do you have in mind? An script that fetches a website and tells you the relevant keywords?

**Comment by roadahead** [comment]
Hi crodas,

Thanks for your comment! I use your script   tested some  long article and try to get relevant keywords from them,but results aren't good enough. so,I think if you provide some tests with good produced results it will be great!  Anyway,thanks for your greate work!

**Comment by crodas** [comment]
Hi @roadahead 

I'm now improving the results for English by filtering candidates using a [POS Tagger](http://en.wikipedia.org/wiki/Part-of-speech_tagging). The bad thing is that it is language dependent. It should be up during the weekend probably.

Cheers,

**Comment by crodas** [comment]
Just pushed the new code, if your text are in English you should definitely see better results. Installing stem `pecl install stem` should help a little bit but not that much.

``` php
require __DIR__ . "/vendor/autoload.php";

use \crodas\TextRank\Config;
use \crodas\TextRank\TextRank;
use \crodas\TextRank\Stopword;

$config = new Config;
$config->addListener(new Stopword);

$textrank = new TextRank($config);
$keywords = $textrank->getKeywords($some_long_text);

var_dump($keywords);
```

Let me know how it goes.
